# Generated by Django 5.2.4 on 2025-08-22 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, default="no_pfp.png", upload_to="pfp"
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=127)),
            ],
        ),
    ]
