# Generated by Django 5.2.4 on 2025-08-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True, default="pfp/no_pfp.png", upload_to="pfp"
            ),
        ),
    ]
