# Generated by Django 5.2.4 on 2025-08-21 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.post",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sell", "Sell/Buy"),
                            ("members", "Find Members"),
                            ("general", "General"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            bases=("core.post",),
        ),
    ]
