# Generated by Django 5.2.4 on 2025-08-21 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=127)),
                ("state", models.CharField(max_length=127)),
                ("postal_code", models.CharField(max_length=63)),
                ("lattitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="EventPost",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.post",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("custom_location", models.CharField(blank=True, max_length=255)),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.venue",
                    ),
                ),
            ],
            bases=("core.post",),
        ),
    ]
