# Generated by Django 5.2.4 on 2025-07-28 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=127)),
                ("state", models.CharField(max_length=127)),
                ("postal_code", models.CharField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="custom_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="custom_city",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="custom_postal_code",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="custom_state",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.venue",
            ),
        ),
    ]
